### ISSUE TITLE
Incompatible with Angular 9

### ISSUE THREAD

**Issue by Barzille** [lula/ngx-summernote#62] opened 2019-11-15 14:18 UTC
With the current version of Angular 9 RC2  I am getting the following error:

    ERROR in ../node_modules/ngx-summernote/lib/ngx-summernote-view.directive.d.ts:1:22 - error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

    1 import { ElementRef, Renderer, AfterViewInit } from '@angular/core';
                       ~~~~~~~~

     ../node_modules/@angular/core/core.d.ts:5555:31
    5555 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

**Comment by lula** [comment] 2019-12-18 11:45
@Barzille haven't tried Angular 9 yet. Keep this issue open until Angular 9 is supported.

**Comment by jmannau** [comment] 2019-12-18 23:36
I have migrated from Renderer to Renderer2 and opened a pull request. This should allow Angular 9 support.

**Comment by llulani** [comment] 2019-12-19 14:07
@jmannau thank you! I'll have a look  during my holidays.

**Comment by kamlesh0606** [comment] 2019-12-28 10:16
I also wait for this update.

**Comment by lula** [comment] 2019-12-30 13:30
Hello guys, pull request have been merged and published to 0.7.1.

Cheers!

**Closed by lula** 2019-12-30 13:30 UTC

**Comment by hvaishnav** [comment] 2020-03-05 07:55
Hello guys , 
  getting this error at this date too.
Does the problem is not resolved yet?

**Comment by lula** [comment] 2020-03-05 07:59
Hello @hvaishnav as far as I can see it is. Do you still have a problem with Renderer2?

**Comment by NidheeshMv** [comment] 2020-04-22 06:41
Hey Team,
Im using Nativescript version 8.2.1 supporting only Renderer. I want to migrate to Angular 9.
getting below issue

node_modules/@nativescript/angular/router/ns-router-link-active.d.ts:1:73 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { AfterContentInit, ElementRef, OnChanges, OnDestroy, QueryList, Renderer } from "@angular/core";
~~~~~~~~

node_modules/@angular/core/core.d.ts:5752:31
5752 export declare abstract class Renderer2 {
~~~~~~~~~
'Renderer2' is declared here.

**Comment by lula** [comment] 2020-04-22 15:25
`Renderer` is not supported anymore in Angular 9. BTW why are you asking this question here and not in Nativescript?

**Comment by dm-bishnoi** [comment] 2020-08-13 06:40
Install  ngx-summernote
